# Generated by Django 4.2.14 on 2024-07-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0004_student_attendance_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
    ]
